disabled_rules: # rule identifiers to exclude from running
  - attributes
  - force_try
  - line_length
  - variable_name
  - file_header
  - force_unwrapping
  - missing_docs
  - closure_end_indentation
  - type_name
  - cyclomatic_complexity
  - type_body_length
  - file_length
  - force_cast
  - legacy_constructor
  - object_literal
  - function_parameter_count
  - class_delegate_protocol
  - weak_delegate
  - sorted_imports

type_body_length:
  - 400 # warning
  - 1000 # error

function_body_length:
  - 400 # warning
  - 1000 # error

line_length:
  - 120 # warning
  - 500 # error

force_cast: warning

excluded:
  - dev
  - Examples/iOS/AnalogSynthX/AnalogSynthX/Extensions/
  - AudioKit/iOS/Audiobus/

opt_in_rules:
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - first_where
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
