site_name: AudioKit
repo_url: https://github.com/AudioKit/AudioKit/

theme:
    name: readthedocs

nav:
    - Home: README.md
    - Migration Guide: MigrationGuide.md
    - Packages:
        - AudioKit: /Packages/AudioKit.md
        - AudioKitUI: /Packages/AudioKitUI.md
        - Develoop AudioKit: /Packages/DeveloopAudioKit.md
        - Dunne AudioKit: /Packages/DunneAudioKit.md
        - Soul AudioKit: /Packages/SoulAudioKit.md
        - Soundpipe AudioKit: /Packages/SoundpipeAudioKit.md
        - Sporth AudioKit: /Packages/SporthAudioKit.md
        - STK AudioKit: /Packages/STKAudioKit.md
    - About:
        - About Us: /About/AboutUs.md
        - Contributing Code: /About/Contributing.md
