module_name: AudioKit
author_name: Aurelius Prochazka
author_url: https://audiokit.io/
github_url: https://github.com/audiokit/AudioKit
min_acl: internal
readme: ../README.md
swift_version: 2.1.1


custom_categories:
  - name: AudioKit Core
    children:
    - AKManager
    - AKTable
    - AKTableType

  - name: MIDI
    children:
    - AKMidi
    - AKMidiEvent
    - AKMidiControl
    - AKMidiStatus
    - AKMidiSystemCommand

  - name: Nodes
    children:
    - AKNode
    - AKOperationEffect
    - AKOperationGenerator

  - name: Analysis Nodes
    children:
    - AKTrackedAmplitude

  - name: Delay Nodes
    children:
    - AKDelay
    - AKVariableDelay

  - name: Distortion Nodes
    children:
    - AKBitCrusher
    - AKClipper
    - AKDecimator
    - AKDistortion
    - AKRingModulator
    - AKTanhDistortion

  - name: Dynamics Nodes
    children:
    - AKDynamicsProcessor
    - AKPeakLimiter

  - name: Filter Nodes
    children:
    - AKAutoWah
    - AKBandPassButterworthFilter
    - AKBandPassFilter
    - AKBandRejectButterworthFilter
    - AKCombFilter
    - AKDCBlock
    - AKEqualizerFilter
    - AKFormantFilter
    - AKHighPassButterworthFilter
    - AKHighPassFilter
    - AKHighShelfFilter
    - AKHighShelfParametricEqualizerFilter
    - AKLowPassButterworthFilter
    - AKLowPassFilter
    - AKLowShelfFilter
    - AKLowShelfParametricEqualizerFilter
    - AKModalResonanceFilter
    - AKMoogLadder
    - AKParametricEQ
    - AKPeakingParametricEqualizerFilter
    - AKRolandTB303Filter
    - AKStringResonator
    - AKThreePoleLowpassFilter
    - AKToneFilter
    - AKToneComplementFilter

  - name: Reverb Nodes
    children:
    - AKChowningReverb
    - AKCostelloReverb
    - AKFlatFrequencyResponseReverb
    - AKReverb
    - AKReverb2

  - name: Oscillator Nodes
    children:
    - AKFMOscillator
    - AKOscillator
    - AKSawtoothOscillator
    - AKSquareWaveOscillator
    - AKTriangleOscillator

  - name: Noise Generator Nodes
    children:
    - AKPinkNoise
    - AKWhiteNoise

  - name: Input Node
    children:
    - AKMicrophone

  - name: Mixing Nodes
    children:
    - AKGain
    - AKMixer

  - name: Playback Nodes
    children:
    - AKAudioPlayer
    - AKSampler
    - AKSequencer
    - AKTimePitch

  - name: Operations
    children:
    - AKOperation
    - AKStereoOperation
    - ak(_:)

  - name: Math Operations
    children:
    - "*(_:_:)"
    - "+(_:_:)"
    - "-(_:_:)"
    - "/(_:_:)"
    - abs(_:)
    - floor(_:)
    - fract(_:)
    - log(_:)
    - log10(_:)
    - max(_:_:)
    - min(_:_:)
    - round(_:)
    - scale(_:minimum:maximum:)

  - name: Random Number Generators
    children:
    - jitter(amplitude:minimumFrequency:maximumFrequency:)
    - randomFloat(_:_:)
    - randomInt(_:)
    - randomNumberPulse(minimum:maximum:updateFrequency:)
    - randomVertexPulse(minimum:maximum:updateFrequency:)

  - name: Noise Generators
    children:
    - pinkNoise(amplitude:)
    - whiteNoise(amplitude:)

  - name: Oscillator Operations
    children:
    - fmOscillator(baseFrequency:carrierMultiplier:modulatingMultiplier:modulationIndex:amplitude:)
    - phasor(frequency:phase:)
    - sawtoothWave(frequency:amplitude:)
    - sineWave(frequency:amplitude:)
    - squareWave(frequency:amplitude:pulseWidth:)
    - triangleWave(frequency:amplitude:)

  - name: Physical Models
    children:
    - pluckedString(frequency:position:pickupPosition:reflectionCoefficent:amplitude:lowestFrequency:)

  - name: Music Operations
    children:
    - metronome(_:)
    - periodicTrigger(_:)
    - portamento(_:)

  - name: Mixing Operations
    children:
    - mix(_:_:t:)
    - pan(_:)

  - name: Plotting Tools
    children:
    - AKAudioOutputPlot
    - AKNodeFFTPlot
    - AKNodeOutputPlot
