
# xcodegen project file for AudioKit frameworks

name: AudioKitGen # when ready, rename this to AudioKit
fileGroups:
  - "README.md"
  - "Common/README.md"
targets:
  AudioKit:
    type: framework
    platform: [macOS, iOS]
    deploymentTarget:
      iOS: "13.0"
      macOS: "10.15"
    info:
      path: Info.plist
    sources:
      - path: Externals
        excludes:
          - "**/*.md" # Would like to include the README files but they need to be kept out of the copy files build phase
          - "AudioKitCore/Sampler/AKCoreSampler.hpp"
          - "AudioKitCore/Synth/AKCoreSynth.hpp"
          - "AudioKitCore/ModulatedDelay/AKModulatedDelay.hpp"
          - "AudioKitCore/ModulatedDelay/AKModulatedDelay_Typedefs.h"
          - "AudioKitCore/Sampler/AKSampler_Typedefs.h"
          - "Soundpipe/test/md5.h"
        headerVisibility: project
      - path: Externals
        includes:
          - "AudioKitCore/Sampler/AKCoreSampler.hpp"
          - "AudioKitCore/Synth/AKCoreSynth.hpp"
          - "AudioKitCore/ModulatedDelay/AKModulatedDelay.hpp"
          - "AudioKitCore/ModulatedDelay/AKModulatedDelay_Typedefs.h"
          - "AudioKitCore/Sampler/AKSampler_Typedefs.h"
          - "Soundpipe/test/md5.h"
      - path: Common
        excludes:
          - "**/*.md"
          - "Internals/AudioKit.h"
          - "Internals/CoreAudio/AKAudioUnit.h"
          - "Internals/CoreAudio/AKDSPBase.hpp"
          - "Internals/CoreAudio/AKGlobals.hpp"
          - "Internals/CoreAudio/AKSoundpipeDSPBase.hpp"
          - "Internals/CoreAudio/Apple Code/DSPKernel.hpp"
          - "Internals/CoreAudio/Apple Code/ParameterRamper.hpp"
          - "Internals/CoreAudio/Bank/AKBankAudioUnit.h"
          - "Internals/CoreAudio/Filter Synth/AKFilterSynthAudioUnit.h"
          - "Internals/CoreAudio/Parameter Rampers/AKLinearParameterRamp.hpp"
          - "Internals/CoreAudio/Parameter Rampers/AKParameterRamp.hpp"
          - "Internals/CoreAudio/Parameter Rampers/AKParameterRampBase.hpp"
          - "Internals/EZAudio/EZAudio.h"
          - "Internals/EZAudio/EZAudioDevice.h"
          - "Internals/EZAudio/EZAudioFFT.h"
          - "Internals/EZAudio/EZAudioFile.h"
          - "Internals/EZAudio/EZAudioFileMarker.h"
          - "Internals/EZAudio/EZAudioFloatConverter.h"
          - "Internals/EZAudio/EZAudioFloatData.h"
          - "Internals/EZAudio/EZAudioPlayer.h"
          - "Internals/EZAudio/EZAudioUtilities.h"
          - "Internals/EZAudio/EZMicrophone.h"
          - "Internals/EZAudio/EZOutput.h"
          - "Internals/EZAudio/EZRecorder.h"
          - "Internals/Hardware/Microphone Tracker/AKMicrophoneTrackerEngine.h"
          - "Internals/Sporth Custom Ugens/AKSporthStack.h"
          - "Internals/Utilities/AKInterop.h"
          - "Internals/Utilities/Circular Buffer/TPCircularBuffer+Unit.h"
          - "Internals/Utilities/Circular Buffer/TPCircularBuffer.h"
          - "Internals/Utilities/DebugDSP.h"
          - "Internals/Utilities/Exception Catcher/ExceptionCatcher.h"
          - "Internals/Utilities/Timeline/AKTimeline.h"
          - "Nodes/Analysis/Amplitude Tracker/AKAmplitudeTrackerAudioUnit.h"
          - "Nodes/Analysis/Frequency Tracker/AKFrequencyTrackerAudioUnit.h"
          - "Nodes/Callback Instrument/AKCallbackInstrumentAudioUnit.h"
          - "Nodes/Effects/AudioKit Operation-Based Effect/AKOperationEffectAudioUnit.h"
          - "Nodes/Effects/Modulation/Common/AKModulatedDelayDSP.hpp"
          - "Nodes/Generators/AudioKit Operation-Based Generator/AKOperationGeneratorAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/FM Oscillator Filter Synth/AKFMOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/Morphing Oscillator Filter Synth/AKMorphingOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/Oscillator Filter Synth/AKOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/Phase Distortion Filter Synth/AKPhaseDistortionOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/PWM Filter Synth/AKPWMOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/FM Oscillator Bank/AKFMOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Polysynths/Morphing Oscillator Bank/AKMorphingOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Polysynths/Oscillator Bank/AKOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Polysynths/Phase Distortion Oscillator Bank/AKPhaseDistortionOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Polysynths/PWM Oscillator Bank/AKPWMOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Synth/AKSynthDSP.hpp"
          - "Nodes/Mixing/Automation/AKParameterAutomation.hpp"
          - "Nodes/Playback/AKSamplerMetronome.h"
          - "Nodes/Playback/Samplers/Apple Sampler/AKPresetManager.h"
          - "Nodes/Playback/Samplers/Disk Streamer/AKDiskStreamerAudioUnit.h"
          - "Nodes/Playback/Samplers/Sampler/AKSamplerDSP.hpp"
          - "Nodes/Playback/Samplers/Wave Table/AKWaveTableAudioUnit.h"
          - "Sequencing/Sequencer/AKSequencerEngine.hpp"
          - "Taps/Lazy Tap/AKLazyTap.h"
          - "Taps/Render Tap/AKRenderTap.h"
          - "Taps/Timeline Tap/AKTimelineTap.h"
          - "User Interface/**"
        headerVisibility: project
      - path: Common
        includes:
          - "Internals/AudioKit.h"
          - "Internals/CoreAudio/AKAudioUnit.h"
          - "Internals/CoreAudio/AKDSPBase.hpp"
          - "Internals/CoreAudio/AKGlobals.hpp"
          - "Internals/CoreAudio/AKSoundpipeDSPBase.hpp"
          - "Internals/CoreAudio/Apple Code/DSPKernel.hpp"
          - "Internals/CoreAudio/Apple Code/ParameterRamper.hpp"
          - "Internals/CoreAudio/Bank/AKBankAudioUnit.h"
          - "Internals/CoreAudio/Filter Synth/AKFilterSynthAudioUnit.h"
          - "Internals/CoreAudio/Parameter Rampers/AKLinearParameterRamp.hpp"
          - "Internals/CoreAudio/Parameter Rampers/AKParameterRamp.hpp"
          - "Internals/CoreAudio/Parameter Rampers/AKParameterRampBase.hpp"
          - "Internals/EZAudio/EZAudio.h"
          - "Internals/EZAudio/EZAudioDevice.h"
          - "Internals/EZAudio/EZAudioFFT.h"
          - "Internals/EZAudio/EZAudioFile.h"
          - "Internals/EZAudio/EZAudioFileMarker.h"
          - "Internals/EZAudio/EZAudioFloatConverter.h"
          - "Internals/EZAudio/EZAudioFloatData.h"
          - "Internals/EZAudio/EZAudioPlayer.h"
          - "Internals/EZAudio/EZAudioUtilities.h"
          - "Internals/EZAudio/EZMicrophone.h"
          - "Internals/EZAudio/EZOutput.h"
          - "Internals/EZAudio/EZRecorder.h"
          - "Internals/Hardware/Microphone Tracker/AKMicrophoneTrackerEngine.h"
          - "Internals/Sporth Custom Ugens/AKSporthStack.h"
          - "Internals/Utilities/AKInterop.h"
          - "Internals/Utilities/Circular Buffer/TPCircularBuffer+Unit.h"
          - "Internals/Utilities/Circular Buffer/TPCircularBuffer.h"
          - "Internals/Utilities/DebugDSP.h"
          - "Internals/Utilities/Exception Catcher/ExceptionCatcher.h"
          - "Internals/Utilities/Timeline/AKTimeline.h"
          - "Nodes/Analysis/Amplitude Tracker/AKAmplitudeTrackerAudioUnit.h"
          - "Nodes/Analysis/Frequency Tracker/AKFrequencyTrackerAudioUnit.h"
          - "Nodes/Callback Instrument/AKCallbackInstrumentAudioUnit.h"
          - "Nodes/Effects/AudioKit Operation-Based Effect/AKOperationEffectAudioUnit.h"
          - "Nodes/Effects/Modulation/Common/AKModulatedDelayDSP.hpp"
          - "Nodes/Generators/AudioKit Operation-Based Generator/AKOperationGeneratorAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/FM Oscillator Filter Synth/AKFMOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/Morphing Oscillator Filter Synth/AKMorphingOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/Oscillator Filter Synth/AKOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/Phase Distortion Filter Synth/AKPhaseDistortionOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/Filter Polysynths/PWM Filter Synth/AKPWMOscillatorFilterSynthAudioUnit.h"
          - "Nodes/Generators/Polysynths/FM Oscillator Bank/AKFMOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Polysynths/Morphing Oscillator Bank/AKMorphingOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Polysynths/Oscillator Bank/AKOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Polysynths/Phase Distortion Oscillator Bank/AKPhaseDistortionOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Polysynths/PWM Oscillator Bank/AKPWMOscillatorBankAudioUnit.h"
          - "Nodes/Generators/Synth/AKSynthDSP.hpp"
          - "Nodes/Mixing/Automation/AKParameterAutomation.hpp"
          - "Nodes/Playback/AKSamplerMetronome.h"
          - "Nodes/Playback/Samplers/Apple Sampler/AKPresetManager.h"
          - "Nodes/Playback/Samplers/Disk Streamer/AKDiskStreamerAudioUnit.h"
          - "Nodes/Playback/Samplers/Sampler/AKSamplerDSP.hpp"
          - "Nodes/Playback/Samplers/Wave Table/AKWaveTableAudioUnit.h"
          - "Sequencing/Sequencer/AKSequencerEngine.hpp"
          - "Taps/Lazy Tap/AKLazyTap.h"
          - "Taps/Render Tap/AKRenderTap.h"
          - "Taps/Timeline Tap/AKTimelineTap.h"
    settings:
      GCC_PREPROCESSOR_DEFINITIONS: "$(inherited) AUDIOKIT=1 NO_LIBSNDFILE=1"
      PRODUCT_BUNDLE_IDENTIFIER: io.audiokit.framework

  AudioKit_tests:
    type: bundle.unit-test
    platform: [macOS, iOS]
    sources:
      - path: ../Tests/TestCases
        excludes:
          - "AKDynaRageCompressorTests.swift"
      - path: ../Developer/Common
        includes:
          - "*.wav"
    dependencies:
      - target: AudioKit_${platform}
