name: CI

on: [push, pull_request]

jobs:
  build-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        env:
          [PLATFORMS: iOS, PLATFORMS: macOS, PLATFORMS: tvOS]
    
      fail-fast: true

    steps:
    - name: Check out AudioKit
      uses: actions/checkout@v2

    - name: Build Frameworks
      run: |
        cd Frameworks
        ./build_frameworks.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.env.PLATFORMS }}
        path: Frameworks/AudioKit-${{ matrix.env.PLATFORMS }}


 