# GitHub Actions for AudioKit: includes builds, tests and releases
name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        xcode_version: ['11.6', '12_beta']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out AudioKit
        uses: actions/checkout@v2
      - name: Generate Xcode Project 
        run: |
          set -euo pipefail
          swift package generate-xcodeproj --xcconfig-overrides AudioKit.xcconfig
      - name: Build AudioKit
        run: |
          set -euo pipefail
          xcodebuild -project AudioKit.xcodeproj -scheme AudioKit-Package clean build | xcpretty -c
      - name: Run Tests
        run: |
          set -euo pipefail
          xcodebuild -project AudioKit.xcodeproj -scheme AudioKit-Package test | xcpretty -c
