# GitHub Actions for AudioKit: includes builds, tests and releases
name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        xcode_version: ['11.6', '12_beta']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out AudioKit
        uses: actions/checkout@v2
      - name: Build AudioKit 
        run: swift build 
