name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        env:
          [PLATFORMS: iOS, PLATFORMS: macOS, PLATFORMS: tvOS]
      fail-fast: true

    steps:
    - name: Install additional packages
      run: brew install swiftlint

    - name: Check out AudioKit
      uses: actions/checkout@v2

    - name: Build Frameworks
      run: |
        cd Frameworks
        ./build_frameworks.sh
      env:
        PLATFORMS: ${{ matrix.env.PLATFORMS }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.env.PLATFORMS }}
        path: Frameworks/AudioKit-${{ matrix.env.PLATFORMS }}

  test:
    needs: build
    runs-on: macos-latest

    steps:
    - name: Download iOS Frameworks
      uses: actions/checkout@v1
      with:
        name: iOS
    - name: Download macOS Frameworks
      uses: actions/checkout@v1
      with:
        name: macOS
    - name: Download tvOS Frameworks
      uses: actions/checkout@v1
      with:
        name: tvOS

    - name: Check out AudioKit
      uses: actions/checkout@v2

    - name: Run tests
      run: ls -l
 