name: CI

on: [push, pull_request]

jobs:
  # Run the build for each platform in parallel
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        env:
          [PLATFORMS: iOS, PLATFORMS: macOS, PLATFORMS: tvOS]
      fail-fast: true

    steps:
    - name: Install additional packages
      run: brew install swiftlint

    - name: Check out AudioKit
      uses: actions/checkout@v2

    - name: Build Frameworks
      run: |
        cd Frameworks
        ./build_frameworks.sh
      env:
        PLATFORMS: ${{ matrix.env.PLATFORMS }}

    - name: Upload built frameworks
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.env.PLATFORMS }}
        path: Frameworks/AudioKit-${{ matrix.env.PLATFORMS }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-${{ matrix.env.PLATFORMS }}
        path: Frameworks/build

  # Reassemble the builds, put together the XCFramework
  xcframework:
    needs: build
    runs-on: macos-latest

    steps:
    - name: Check out AudioKit
      uses: actions/checkout@v2

    - name: Download iOS build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build-iOS
        path: Frameworks/build
    - name: Download macOS build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build-macOS
        path: Frameworks/build
    - name: Download tvOS build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build-tvOS
        path: Frameworks/build

    - name: Build XCFramework
      run: |
        cd Frameworks
        mkdir release
        ./build_xcframework.sh release

    - name: Upload XCFramework artifacts
      uses: actions/upload-artifact@v1
      with:
        name: XCFrameworks
        path: Frameworks/release

  # Perform unit tests in parallel
  test:
    needs: build
    runs-on: macos-latest
    strategy:
      matrix:
        env:
          [PLATFORMS: iOS, PLATFORMS: macOS, PLATFORMS: tvOS]
      fail-fast: false

    steps:
    - name: Check out AudioKit
      uses: actions/checkout@v2
    
    - name: Download built frameworks
      uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.env.PLATFORMS }}
        path: Frameworks/AudioKit-${{ matrix.env.PLATFORMS }}

    - name: Run unit tests
      run: ./Tests/test-${{ matrix.env.PLATFORMS }}.sh

  # Upload staging builds to S3
  staging:
    needs: xcframework
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
    - name: Check out AudioKit
      uses: actions/checkout@v2
    - name: Download XCFramework
      uses: actions/download-artifact@v1
      with:
        name: XCFramework
        path: Frameworks
    - name: Upload to S3
      run: |
        cd Frameworks
        ls -lR
        zip -9r AudioKit.xcframework.zip XCFramework
        aws s3 ls s3://files.audiokit.io/staging/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Upload release assets for tags
  release:
    needs: xcframework
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Check out AudioKit
      uses: actions/checkout@v2

