# GitHub Actions for AudioKit: includes builds, tests and releases
name: CI

on: [push, pull_request]
env:
  XCODE_VER: 11.6

jobs:
  test:
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{XCODE_VER}}.app
    steps:
      - name: Check out AudioKit
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test
